services:
  db:
    # This image includes PostGIS
    image: timescale/timescaledb-ha:pg16-oss
    container_name: sensing_app_db
    restart: always
    environment:
      - POSTGRES_DB=sensing_db
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d # This auto-runs your schema on startup

  grafana:
    image: grafana/grafana-oss:latest
    container_name: sensing_app_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
    depends_on:
      - db
    restart: always
