services:
  db:
    image: timescale/timescaledb-ha:pg16-oss
    container_name: sensing_app_db
    restart: always
    environment:
      - POSTGRES_DB=sensing_db
      - POSTGRES_PASSWORD=dev_password
    ports:
      - "5432:5432"
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d # This auto-runs your schema on startup
